# config/rag_config.yaml
system:
  name: "Enhanced Breeding RAG"
  version: "1.0.0"
  
embeddings:
  model: "sentence-transformers/all-MiniLM-L6-v2"
  dimension: 384
  batch_size: 32
  
vector_database:
  type: "chromadb"
  persist_directory: "db/chroma_breeding"
  collection_name: "breeding_intelligence"
  
data_processing:
  chunk_size: 500
  chunk_overlap: 50
  max_chunks_per_document: 20
  
retrieval:
  default_k: 8
  max_k: 20
  similarity_threshold: 0.7
  
response_generation:
  max_tokens: 1000
  temperature: 0.7
  confidence_threshold: 0.6

breeding_domain:
  programs:
    - MR1  # High Rainfall
    - MR2  # Medium Rainfall  
    - MR3  # Low Rainfall/Drought
    - MR4  # Irrigated
    
  key_traits:
    - yield
    - disease_resistance
    - drought_tolerance
    - quality_traits
    - adaptation_traits
    
  analysis_types:
    - performance_analysis
    - genetic_analysis
    - economic_analysis
    - strategic_planning
